# Generated by Django 5.2.7 on 2025-10-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='listings.band')),
            ],
        ),
    ]
